### ISSUE TITLE
options.txt lowercase

### ISSUE THREAD

**Issue by Sgeets** [wa2nfn/morse_code_practice_text#3]
Just a minor aesthetic one.  Have a look in the supplied option.txt file line 71-72.  This option is not correct.  The one at the EOF  is working.

```
# Print output in all capitals. (default false = lowercase)
lowerCase=flase
 
...

# make all output lowercase
lowercase
```

**Comment by wa2nfn** [comment]
You are right. It was a recent change and I realize my poor spelling. Many people think it’s two words, but it’s not.  Based on my reply, is the slashed zero still an issue? As I said data written to -outFile will be a set snarf zero and therefore software like lcwo, grfon etc will send da da da da da73 Bill=30=On Mar 18, 2023, at 3:33 PM, Sgeets ***@***.***> wrote:﻿
Just a minor aesthetic one.  Have a look in the supplied option.txt file line 71-72.  This option is not correct.  The one at the EOF  is working.
# Print output in all capitals. (default false = lowercase)
lowerCase=flase
 
...

# make all output lowercase
lowercase

**Comment by wa2nfn** [comment]
git updated
fixed
 option.tx
add option -zero which leaves displayed zeros as a normal digit
all go files sent through gofmt hopefully a little neater

The man page is not updated, but seems only the UserGuide has been used.

73 wa2nfn

PS NOT yet in qsl.net for download

**Comment by Sgeets** [comment]
Thx !
